import jsPDF from 'jspdf';
import { formatMagnitude, formatCoordinates, formatFullDate, formatNumber } from './formatters';

export const generateAftershockPDF = (earthquake, predictions) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const margin = 20;
  const lineHeight = 7;
  let yPosition = 20;

  // Helper function to add text with word wrap
  const addText = (text, fontSize = 12, isBold = false) => {
    doc.setFontSize(fontSize);
    doc.setFont('helvetica', isBold ? 'bold' : 'normal');
    const lines = doc.splitTextToSize(text, pageWidth - 2 * margin);
    doc.text(lines, margin, yPosition);
    yPosition += lines.length * lineHeight;
  };

  // Helper function to add a section with background
  const addSection = (title) => {
    yPosition += 5;
    doc.setFillColor(255, 107, 53); // Orange
    doc.rect(margin - 5, yPosition - 5, pageWidth - 2 * margin + 10, 10, 'F');
    doc.setTextColor(255, 255, 255);
    addText(title, 14, true);
    doc.setTextColor(0, 0, 0);
    yPosition += 3;
  };

  // Check if we need a new page
  const checkPageBreak = (requiredSpace = 40) => {
    if (yPosition > doc.internal.pageSize.height - requiredSpace) {
      doc.addPage();
      yPosition = 20;
    }
  };

  // Title
  doc.setFillColor(10, 14, 39);
  doc.rect(0, 0, pageWidth, 40, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Aftershock Forecast Report', pageWidth / 2, 25, { align: 'center' });
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by Aftershock Monitor', pageWidth / 2, 32, { align: 'center' });
  
  yPosition = 50;
  doc.setTextColor(0, 0, 0);

  // Mainshock Information
  addSection('Mainshock Information');
  addText(`Magnitude: ${formatMagnitude(earthquake.magnitude)}`, 12, true);
  addText(`Location: ${earthquake.place}`);
  addText(`Coordinates: ${formatCoordinates(earthquake.latitude, earthquake.longitude)}`);
  addText(`Depth: ${Math.round(earthquake.depth)} km`);
  addText(`Time: ${formatFullDate(earthquake.time)}`);

  checkPageBreak();

  // Risk Assessment
  addSection('Risk Assessment');
  const risk = predictions.risk_assessment;
  doc.setTextColor(
    risk.level === 'CRITICAL' ? 220 : risk.level === 'HIGH' ? 245 : 251,
    risk.level === 'CRITICAL' ? 38 : risk.level === 'HIGH' ? 158 : 191,
    risk.level === 'CRITICAL' ? 38 : risk.level === 'HIGH' ? 11 : 36
  );
  addText(`Risk Level: ${risk.level}`, 14, true);
  doc.setTextColor(0, 0, 0);
  addText(risk.description);
  
  yPosition += 3;
  addText('Risk Factors:', 11, true);
  risk.factors.forEach(factor => {
    addText(`• ${factor}`, 10);
  });

  checkPageBreak();

  // Safety Recommendations
  addSection('Safety Recommendations');
  risk.recommendations.forEach((rec, idx) => {
    addText(`${idx + 1}. ${rec}`, 10);
  });

  checkPageBreak();

  // Expected Aftershocks
  addSection('Expected Aftershocks Over Time');
  yPosition += 5;

  // Create table
  const tableData = [];
  Object.entries(predictions.forecasts).forEach(([key, forecast]) => {
    tableData.push([
      forecast.days === 1 ? 'Next 24 Hours' : `Day ${forecast.days}`,
      formatNumber(forecast.expected_aftershocks),
      formatNumber(forecast.cumulative_expected)
    ]);
  });

  // Simple table
  const colWidth = (pageWidth - 2 * margin) / 3;
  
  // Table header
  doc.setFillColor(240, 240, 240);
  doc.rect(margin, yPosition, colWidth, 10, 'F');
  doc.rect(margin + colWidth, yPosition, colWidth, 10, 'F');
  doc.rect(margin + 2 * colWidth, yPosition, colWidth, 10, 'F');
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('Time Period', margin + 5, yPosition + 7);
  doc.text('Expected/Day', margin + colWidth + 5, yPosition + 7);
  doc.text('Total Expected', margin + 2 * colWidth + 5, yPosition + 7);
  
  yPosition += 10;
  doc.setFont('helvetica', 'normal');

  // Table rows
  tableData.forEach(row => {
    doc.text(row[0], margin + 5, yPosition + 7);
    doc.text(row[1], margin + colWidth + 5, yPosition + 7);
    doc.text(row[2], margin + 2 * colWidth + 5, yPosition + 7);
    yPosition += 10;
  });

  checkPageBreak();

  // Magnitude Probabilities
  addSection('Magnitude Probabilities');
  yPosition += 5;

  Object.entries(predictions.magnitude_probabilities).forEach(([key, prob]) => {
    addText(
      `${key} or larger: ${(prob.percentage).toFixed(1)}% probability (${formatNumber(prob.expected_count)} expected)`,
      10
    );
  });

  checkPageBreak();

  // Model Information
  addSection('Model Information');
  const model = predictions.model_info;
  addText(`Region ID: ${model.region_id}`);
  addText(`Model Source: ${model.source.replace('_', ' ').toUpperCase()}`);
  addText(`Data Quality: ${model.quality.toUpperCase()}`);
  addText(`Training Data: ${model.training_sequences} sequences, ${model.training_aftershocks} aftershocks`);
  addText(`Model Accuracy: R² = ${model.omori_r_squared.toFixed(3)}`);

  checkPageBreak(60);

  // Disclaimer
  yPosition += 10;
  doc.setFillColor(254, 243, 199);
  doc.rect(margin - 5, yPosition - 5, pageWidth - 2 * margin + 10, 45, 'F');
  doc.setTextColor(120, 53, 15);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('⚠ IMPORTANT DISCLAIMER', margin, yPosition + 5);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  const disclaimer = 'These predictions are probabilistic forecasts based on historical seismic patterns and statistical models. While trained on 35 years of data and validated using rigorous methods, earthquake prediction remains an inherently uncertain science. Always follow official guidance from local authorities and seismological institutions. This tool should be used as supplementary information, not as a replacement for official warnings.';
  const disclaimerLines = doc.splitTextToSize(disclaimer, pageWidth - 2 * margin - 10);
  doc.text(disclaimerLines, margin, yPosition + 12);
  doc.setTextColor(0, 0, 0);

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Page ${i} of ${pageCount} | Generated: ${new Date().toLocaleString()}`,
      pageWidth / 2,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    );
  }

  // Save the PDF
  const fileName = `aftershock_report_${formatMagnitude(earthquake.magnitude)}_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
};
